---
ID: "aa244095-4de8-49bc-8cc9-eeb119141a87"
Parent: "b63c01c2-7fd1-4551-94d3-4f96403a7505"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/User Defined/Healthcheck/Components/Queue Check/Configuration/Database
DB: master
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: /sitecore/system/Modules/Healthcheck Module/Cleanup Lookups/Databases
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Droplist
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200508T061419Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
