---
ID: "af3e06f2-a56d-4ca2-8142-1453183a573d"
Parent: "a64f4366-3d8b-4ec5-9417-f44ac6030951"
Template: "a64f4366-3d8b-4ec5-9417-f44ac6030951"
Path: /sitecore/templates/User Defined/Healthcheck/Components/Windows Service Check/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200420T075316Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "63b8c445-ff44-4985-bd6a-b2d4200cf70d"
    - ID: "a17f9233-805e-4508-ac63-0008a3e89b24"
      Hint: Healthy Message
      Value: "The {0} service is running"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210205T131955Z
