---
ID: "4040954e-2135-4b63-88a4-729c5cbb2648"
Parent: "da5d3dbf-6226-456c-bcf4-cfd5d4f7b2ac"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/User Defined/Healthcheck/Components/XConnectAPI Check/Configuration
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200420T071648Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8623c60f-3b3c-4cd9-b72f-a5e24d5cf850"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210205T131947Z
