---
ID: "a9613eea-8c2f-4cb2-bd5d-465d3bcfa30a"
Parent: "0808ad04-66fc-4839-ac86-6f8f58fcfcfb"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/User Defined/Healthcheck/Components/Search Healthcheck/Configuration
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200323T125400Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "62a60954-88ce-492d-b5ac-77f7d17bb6de"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210205T131947Z
