---
ID: "857aaa78-61c8-42f7-9cc5-8d5c68ef9fd8"
Parent: "3b63c456-768e-4d6e-86a4-5cdbba6d2f98"
Template: "f58502e1-19ec-49e4-a19e-55f99beab821"
Path: /sitecore/system/Modules/Healthcheck Module/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1bf91f7a-573d-43c3-92c3-854c7b1a14a3"
      Hint: Error Level
      Value: Healthy
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200321T095344Z
    - ID: "4862d741-4843-4728-8d6d-48576c0855a7"
      Hint: Recipient Emails
      Value: mihaly.arvai@mirumagency.com
    - ID: "5890d553-86ed-4297-bbc8-3f89a0c42a95"
      Hint: Days
      Value: 1
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "66f6c01c-fa3e-4f89-9b00-a2b9c3d62f70"
      Hint: Sender Name
      Value: Mihaly
    - ID: "84b70fb0-87b7-4892-b8d4-9a7f96f53593"
      Hint: Subject
      Value: Healthcheck
    - ID: "87e5dbf7-db41-4d25-89dc-826b099d391c"
      Hint: Sender Email
      Value: mihaly.arvai@mirumagency.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "adcff659-c7de-4442-a680-0ed75ccd6ac1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210205T131951Z
