---
ID: "c028fd1b-92de-4ede-894c-4110383683f0"
Parent: "aa16ef54-4954-4b4b-9056-537f97e9ee0f"
Template: "f3b3fab1-2a51-41f2-bf30-8c36bc89cf5b"
Path: /sitecore/system/Modules/Healthcheck Module/Components/Application Insights
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0d5613ef-81f3-433f-9957-e35f4fade6f7"
      Hint: Name
      Value: Application Insights
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200402T145957Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d7a1b654-5b30-4ce3-88df-8bdfc82813ec"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210205T131951Z
