---
ID: "4a3d9448-b5e6-4a82-a74c-b2ac379628b0"
Parent: "7eeb1fb3-6a23-46cb-9d43-8919bf4a7bfb"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/User Defined/Healthcheck/Components/Web Job Check/Configuration
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200420T124429Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "83448300-3774-4fd3-ad1a-bcf77b8ec9fb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210205T131947Z
