---
ID: "b283ec0e-0d5d-4939-a450-0af017936f83"
Parent: "03f72a84-a9bc-4cbd-adda-e9ca8871c22b"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/User Defined/Healthcheck/Components/Database Healthcheck/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200321T094151Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
